# Generated by Django 4.0.6 on 2022-09-07 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='منطقه')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'منطقه',
            },
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9, unique=True, verbose_name='کد فایل')),
                ('title', models.CharField(default='خونه', max_length=35, verbose_name='عنوان فایل')),
                ('adress', models.CharField(default='شهرک اکباتان', max_length=68, verbose_name='آدرس')),
                ('nameM', models.CharField(max_length=50, verbose_name='نام مالک')),
                ('melktype', models.CharField(choices=[('آپارتمان', 'آپارتمان'), ('اداری و تجاری', 'اداری و تجاری')], max_length=20, verbose_name='نوع ملک')),
                ('phase', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, null=True, verbose_name='فاز')),
                ('block', models.CharField(blank=True, max_length=4, null=True, verbose_name='بلوک')),
                ('entry', models.CharField(blank=True, max_length=20, null=True, verbose_name='ورودی')),
                ('side', models.CharField(blank=True, choices=[('شمالی', 'شمالی'), ('جنوبی', 'جنوبی'), ('شرقی', 'شرقی'), ('غربی', 'غربی')], max_length=10, null=True, verbose_name='جهت')),
                ('metraj', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='متراژ (متر)')),
                ('room_qty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاق')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طبقه')),
                ('pelak', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=15, verbose_name='موبایل')),
                ('priceM', models.BigIntegerField(blank=True, default='0', null=True, verbose_name='قیمت هر متر  (تومان)')),
                ('priceK', models.BigIntegerField(blank=True, default='0', null=True, verbose_name='قیمت کل  (تومان)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/home', verbose_name='تصویر اصلی')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/home', verbose_name='تصویر دوم')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/home', verbose_name='تصویر سوم')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('storage_room', models.BooleanField(default=False, verbose_name='انباری')),
                ('elevator', models.CharField(blank=True, max_length=30, null=True, verbose_name='پوشش کف')),
                ('building_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن بنا (سال)')),
                ('additional_information', models.TextField(blank=True, max_length=2000, null=True, verbose_name='اطلاعات تکمیلی')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ آگهی')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area', verbose_name='منطقه')),
                ('relname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشاور فروش')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش',
            },
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9, unique=True, verbose_name='کد فایل')),
                ('title', models.CharField(default='خونه', max_length=35, verbose_name='عنوان فایل')),
                ('adress', models.CharField(default='شهرک اکباتان', max_length=68, verbose_name='آدرس')),
                ('nameM', models.CharField(max_length=50, verbose_name='نام مالک')),
                ('melktype', models.CharField(choices=[('آپارتمان', 'آپارتمان'), ('اداری و تجاری', 'اداری و تجاری')], max_length=20, verbose_name='نوع ملک')),
                ('phase', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, null=True, verbose_name='فاز')),
                ('block', models.CharField(blank=True, max_length=4, null=True, verbose_name='بلوک')),
                ('entry', models.CharField(blank=True, max_length=20, null=True, verbose_name='ورودی')),
                ('side', models.CharField(blank=True, choices=[('شمالی', 'شمالی'), ('جنوبی', 'جنوبی'), ('شرقی', 'شرقی'), ('غربی', 'غربی')], max_length=10, null=True, verbose_name='جهت')),
                ('metraj', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='متراژ (متر)')),
                ('room_qty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاق')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طبقه')),
                ('pelak', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=15, verbose_name='موبایل')),
                ('priceR', models.BigIntegerField(blank=True, default='0', null=True, verbose_name='ودیعه  (تومان)')),
                ('priceE', models.BigIntegerField(blank=True, default='0', null=True, verbose_name='اجاره  (تومان)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/home', verbose_name='تصویر اصلی')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/home', verbose_name='تصویر دوم')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/home', verbose_name='تصویر سوم')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('storage_room', models.BooleanField(default=False, verbose_name='انباری')),
                ('elevator', models.CharField(blank=True, max_length=30, null=True, verbose_name='پوشش کف')),
                ('building_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن بنا (سال)')),
                ('additional_information', models.TextField(blank=True, max_length=2000, null=True, verbose_name='اطلاعات تکمیلی')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ آگهی')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area', verbose_name='منطقه')),
                ('relname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشاور فروش')),
            ],
            options={
                'verbose_name': 'رهن',
                'verbose_name_plural': 'رهن',
            },
        ),
    ]
